terraform config file fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,12 +6,17 @@ on:
     - main
   pull_request:
 
+permissions:
+  id-token: write
+  contents: read
+  issues: write
+
+
 jobs:
   terraform:
     name: 'Terraform'
     env:
       ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
       ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
     runs-on: ubuntu-latest
@@ -32,29 +37,32 @@ jobs:
     #     tf_actions_subcommand: 'fmt'
     #     tf_actions_working_dir: "./terraform"
         
-    - name: 'Terraform Init'
-      uses: hashicorp/terraform-github-actions@master
-      with:
-        tf_actions_version: 1.0.0
-        tf_actions_subcommand: 'init'
-        tf_actions_working_dir: "./terraform"
+    - name: Terraform Init
+      run: terraform init
 
-    - name: 'Terraform Validate'
-      uses: hashicorp/terraform-github-actions@master
-      with:
-        tf_actions_version: 1.0.0
-        tf_actions_subcommand: 'validate'
-        tf_actions_working_dir: "./terraform"
+    # Generates an execution plan for Terraform
+    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    - name: Terraform Plan
+      id: tf-plan
+      run: |
+        export exitcode=0
+        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
         
-    - name: 'Terraform Plan'
-      uses: hashicorp/terraform-github-actions@master
+        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+        
+        if [ $exitcode -eq 1 ]; then
+          echo Terraform Plan Failed!
+          exit 1
+        else 
+          exit 0
+        fi
+        
+    # Save plan to artifacts  
+    - name: Publish Terraform Plan
+      uses: actions/upload-artifact@v4
       with:
-        tf_actions_version: 1.0.0
-        tf_actions_subcommand: 'plan'
-        tf_actions_working_dir: "./terraform"
-      env:
-        #this is needed since we are running terraform with read-only permissions
-        ARM_SKIP_PROVIDER_REGISTRATION: true
+        name: tfplan
+        path: tfplan
 
     - name: Terraform Apply
       if: github.ref == 'refs/heads/main'
